In [1]:
import pandas as pd
import yfinance as yf

---

## Tesla Scrape #1: Using Yahoo Finance API
### Accessing historical pricing data:

In [2]:
# Accessing historical pricing data
ticker_symbol = "TSLA"

# Define the start and end dates for the data you want
start_date = "2021-01-01" 
end_date = "2023-12-31"

# Fetch the data using yfinance
data = yf.download(ticker_symbol, start=start_date, end=end_date, interval="1wk")

# Extract the closing prices
closing_prices = data['Close']

# Extract the weekly volume
weekly_volume = data['Volume']

[*********************100%%**********************]  1 of 1 completed

In [3]:
df = pd.DataFrame({'Closing_Prices': closing_prices, 'Weekly_Volume': weekly_volume})

In [4]:
# Adjusting closing prices for a 3-for-1 stock split on 2022-08-15:
# df.loc['2022-08-15', 'Closing_Price'] /= 3

In [5]:
# Justify why the close column was modified- TSLA stock splits affect price. Clsoe really equals closing price * volumne outstanding = market cap

In [6]:
# Saving df to .csv
df.to_csv('../data/df_tsla_pricing.csv', index=True)

---

### Calling various attributes/methods related to TSLA financials:

In [7]:
# Instantiates the TSLA ticker to access various attributes/methods related to TSLA stock (but not historical pricing data)
tsla = yf.Ticker("TSLA")

In [8]:
# get all stock info
tsla.info

{'address1': '1 Tesla Road',
 'city': 'Austin',
 'state': 'TX',
 'zip': '78725',
 'country': 'United States',
 'phone': '512 516 8177',
 'website': 'https://www.tesla.com',
 'industry': 'Auto Manufacturers',
 'industryKey': 'auto-manufacturers',
 'industryDisp': 'Auto Manufacturers',
 'sector': 'Consumer Cyclical',
 'sectorKey': 'consumer-cyclical',
 'sectorDisp': 'Consumer Cyclical',
 'longBusinessSummary': 'Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems in the United States, China, and internationally. It operates in two segments, Automotive, and Energy Generation and Storage. The Automotive segment offers electric vehicles, as well as sells automotive regulatory credits; and non-warranty after-sales vehicle, used vehicles, retail merchandise, and vehicle insurance services. This segment also provides sedans and sport utility vehicles through direct and used vehicle sales, a network of Tesla Superchargers, and in-app upgrades; purchase financing and leasing services; services for electric vehicles through its company-owned service locations and Tesla mobile service technicians; and vehicle limited warranties and extended service plans. The Energy Generation and Storage segment engages in the design, manufacture, installation, sale, and leasing of solar energy generation and energy storage products, and related services to residential, commercial, and industrial customers and utilities through its website, stores, and galleries, as well as through a network of channel partners; and provision of service and repairs to its energy product customers, including under warranty, as well as various financing options to its solar customers. The company was formerly known as Tesla Motors, Inc. and changed its name to Tesla, Inc. in February 2017. Tesla, Inc. was incorporated in 2003 and is headquartered in Austin, Texas.',
 'fullTimeEmployees': 127855,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Elon R. Musk',
   'age': 50,
   'title': 'Technoking of Tesla, CEO & Director',
   'yearBorn': 1972,
   'fiscalYear': 2022,
   'totalPay': 0,
   'exercisedValue': 0,
   'unexercisedValue': 27819718656},
  {'maxAge': 1,
   'name': 'Mr. Andrew D. Baglino',
   'age': 41,
   'title': 'Sr. VP of Powertrain & Energy Engineering',
   'yearBorn': 1981,
   'fiscalYear': 2022,
   'totalPay': 303000,
   'exercisedValue': 33866368,
   'unexercisedValue': 57355632},
  {'maxAge': 1,
   'name': 'Mr. Vaibhav  Taneja',
   'age': 44,
   'title': 'CFO, Corp. Controller & Chief Accounting Officer',
   'yearBorn': 1978,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Martin  Viecha',
   'title': 'Sr. Director for Investor Relations',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Alan  Prescott',
   'age': 43,
   'title': 'VP of Legal',
   'yearBorn': 1979,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Dave  Arnold',
   'title': 'Sr. Director of Global Communications',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Brian  Scelfo',
   'title': 'Sr. Director of Corp. Devel.',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jeffrey Brian Straubel',
   'age': 46,
   'title': 'Independent Director',
   'yearBorn': 1976,
   'fiscalYear': 2018,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Franz  von Holzhausen',
   'title': 'Chief Designer',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Xiaotong  Zhu',
   'age': 42,
   'title': 'Sr. VP of Automotive',
   'yearBorn': 1980,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 8,
 'boardRisk': 9,
 'compensationRisk': 8,
 'shareHolderRightsRisk': 9,
 'overallRisk': 9,
 'governanceEpochDate': 1696118400,
 'compensationAsOfEpochDate': 1672444800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 259.67,
 'open': 257.75,
 'dayLow': 257.65,
 'dayHigh': 268.94,
 'regularMarketPreviousClose': 259.67,
 'regularMarketOpen': 257.75,
 'regularMarketDayLow': 257.65,
 'regularMarketDayHigh': 268.94,
 'payoutRatio': 0.0,
 'beta': 2.247148,
 'trailingPE': 75.653206,
 'forwardPE': 60.385326,
 'volume': 72696202,
 'regularMarketVolume': 72696202,
 'averageVolume': 115971551,
 'averageVolume10days': 117777550,
 'averageDailyVolume10Day': 117777550,
 'bid': 266.81,
 'ask': 266.8,
 'bidSize': 1100,
 'askSize': 1300,
 'marketCap': 845231226880,
 'fiftyTwoWeekLow': 101.81,
 'fiftyTwoWeekHigh': 299.29,
 'priceToSalesTrailing12Months': 8.989144,
 'fiftyDayAverage': 250.3998,
 'twoHundredDayAverage': 208.94424,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'USD',
 'enterpriseValue': 810708762624,
 'profitMargins': 0.1297,
 'floatShares': 2713606570,
 'sharesOutstanding': 3173989888,
 'sharesShort': 84724119,
 'sharesShortPriorMonth': 81763698,
 'sharesShortPreviousMonthDate': 1692057600,
 'dateShortInterest': 1694736000,
 'sharesPercentSharesOut': 0.026700001,
 'heldPercentInsiders': 0.13043,
 'heldPercentInstitutions': 0.44206002,
 'shortRatio': 0.7,
 'shortPercentOfFloat': 0.0307,
 'impliedSharesOutstanding': 3173989888,
 'bookValue': 16.109,
 'priceToBook': 16.531088,
 'lastFiscalYearEnd': 1672444800,
 'nextFiscalYearEnd': 1703980800,
 'mostRecentQuarter': 1688083200,
 'earningsQuarterlyGrowth': 0.197,
 'netIncomeToCommon': 12234999808,
 'trailingEps': 3.52,
 'forwardEps': 4.38,
 'pegRatio': 9.07,
 'lastSplitFactor': '3:1',
 'lastSplitDate': 1661385600,
 'enterpriseToRevenue': 8.622,
 'enterpriseToEbitda': 48.265,
 '52WeekChange': 0.19939959,
 'SandP52WeekChange': 0.20809507,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'TSLA',
 'underlyingSymbol': 'TSLA',
 'shortName': 'Tesla, Inc.',
 'longName': 'Tesla, Inc.',
 'firstTradeDateEpochUtc': 1277818200,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': 'ec367bc4-f92c-397c-ac81-bf7b43cffaf7',
 'messageBoardId': 'finmb_27444752',
 'gmtOffSetMilliseconds': -14400000,
 'currentPrice': 266.2993,
 'targetHighPrice': 400.0,
 'targetLowPrice': 24.33,
 'targetMeanPrice': 238.93,
 'targetMedianPrice': 265.0,
 'recommendationMean': 2.7,
 'recommendationKey': 'hold',
 'numberOfAnalystOpinions': 37,
 'totalCash': 23075000320,
 'totalCashPerShare': 7.27,
 'ebitda': 16796999680,
 'totalDebt': 5810999808,
 'quickRatio': 0.968,
 'currentRatio': 1.59,
 'totalRevenue': 94027997184,
 'debtToEquity': 11.136,
 'revenuePerShare': 29.751,
 'returnOnAssets': 0.0994,
 'returnOnEquity': 0.27139,
 'grossProfits': 20853000000,
 'freeCashflow': 3028124928,
 'operatingCashflow': 13955999744,
 'earningsGrowth': 0.2,
 'revenueGrowth': 0.472,
 'grossMargins': 0.21486,
 'ebitdaMargins': 0.17864001,
 'operatingMargins': 0.13456,
 'financialCurrency': 'USD',
 'trailingPegRatio': 2.2545}

In [9]:
# get historical market data
hist = tsla.history(period="1y")

In [10]:
# show meta information about the history (requires history() to be called first)
tsla.history_metadata

{'currency': 'USD',
 'symbol': 'TSLA',
 'exchangeName': 'NMS',
 'instrumentType': 'EQUITY',
 'firstTradeDate': 1277818200,
 'regularMarketTime': 1696955321,
 'gmtoffset': -14400,
 'timezone': 'EDT',
 'exchangeTimezoneName': 'America/New_York',
 'regularMarketPrice': 266.3,
 'chartPreviousClose': 222.96,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'timezone': 'EDT',
   'end': 1696944600,
   'start': 1696924800,
   'gmtoffset': -14400},
  'regular': {'timezone': 'EDT',
   'end': 1696968000,
   'start': 1696944600,
   'gmtoffset': -14400},
  'post': {'timezone': 'EDT',
   'end': 1696982400,
   'start': 1696968000,
   'gmtoffset': -14400}},
 'dataGranularity': '1d',
 'range': '1y',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

In [11]:
# show actions, dividends, splits
tsla.actions
tsla.dividends
tsla.splits

Series([], Name: Stock Splits, dtype: float64)

In [12]:
# show share count
tsla.get_shares_full(start="2022-01-01", end=None)

2022-02-04 00:00:00-05:00    1020630016
2022-02-05 00:00:00-05:00    1004259968
2022-02-08 00:00:00-05:00    1033510016
2022-02-11 00:00:00-05:00    1033510016
2022-03-04 00:00:00-05:00    1083500032
2022-03-05 00:00:00-05:00    1033510016
2022-03-15 00:00:00-04:00    1072590016
2022-03-17 00:00:00-04:00    1033510016
2022-03-28 00:00:00-04:00    1036860032
2022-03-31 00:00:00-04:00    1033510016
2022-04-01 00:00:00-04:00    1049230016
2022-04-02 00:00:00-04:00    1033510016
2022-04-04 00:00:00-04:00    1033510016
2022-04-29 00:00:00-04:00    1036009984
2022-07-01 00:00:00-04:00    1036390016
2022-07-26 00:00:00-04:00    1044489984
2022-08-19 00:00:00-04:00    1048380032
2022-08-20 00:00:00-04:00    1044489984
2022-08-29 00:00:00-04:00    3133469952
2022-09-02 00:00:00-04:00    3133469952
2022-09-15 00:00:00-04:00    3024950016
2022-09-16 00:00:00-04:00    3121710080
2022-09-17 00:00:00-04:00    3133469952
2022-10-12 00:00:00-04:00    3226970112
2022-10-13 00:00:00-04:00    3133469952
2022-10-26 00:00:00-04:00    3157750016
2022-11-08 00:00:00-05:00    3324229888
2022-11-10 00:00:00-05:00    3157750016
2022-12-06 00:00:00-05:00    3372539904
2022-12-07 00:00:00-05:00    3157750016
2023-01-04 00:00:00-05:00    3598259968
2023-01-06 00:00:00-05:00    3157750016
2023-02-02 00:00:00-05:00    3164100096
2023-03-16 00:00:00-04:00    3164100096
2023-03-16 00:00:00-04:00    3211770112
2023-03-25 00:00:00-04:00    3194180096
2023-03-25 00:00:00-04:00    3164100096
2023-03-30 00:00:00-04:00    3242540032
2023-04-01 00:00:00-04:00    3362099968
2023-04-01 00:00:00-04:00    3164100096
2023-04-04 00:00:00-04:00    3370909952
2023-04-05 00:00:00-04:00    3164100096
2023-04-06 00:00:00-04:00    3284509952
2023-04-07 00:00:00-04:00    3292679936
2023-04-07 00:00:00-04:00    3164100096
2023-04-08 00:00:00-04:00    3169309952
2023-04-13 00:00:00-04:00    3169309952
2023-04-25 00:00:00-04:00    3169499904
2023-05-03 00:00:00-04:00    3199559936
2023-05-04 00:00:00-04:00    3169499904
2023-05-14 00:00:00-04:00    3180069888
2023-05-16 00:00:00-04:00    3169499904
2023-07-19 00:00:00-04:00    3201809920
2023-07-20 00:00:00-04:00    3169499904
2023-08-22 00:00:00-04:00    3173989888
dtype: int64

In [13]:
# show financials:

# - income statement
tsla_is_annual = tsla.income_stmt
tsla_is_quart = tsla.quarterly_income_stmt

# - balance sheet
tsla_bs_annual = tsla.balance_sheet
tsla_bs_quart = tsla.quarterly_balance_sheet

# - cash flow statement
tsla_cf_annual = tsla.cashflow
tsla_cf_quart = tsla.quarterly_cashflow

In [14]:
tsla_is_annual

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Tax Effect Of Unusual Items,-14080000.0,2970000.0,0.0,-40230000.0
Tax Rate For Calcs,0.08,0.11,0.25,0.27
Normalized EBITDA,17833000000.0,9598000000.0,4224000000.0,2323000000.0
Total Unusual Items,-176000000.0,27000000.0,0.0,-149000000.0
Total Unusual Items Excluding Goodwill,-176000000.0,27000000.0,0.0,-149000000.0
Net Income From Continuing Operation Net Minority Interest,12583000000.0,5519000000.0,690000000.0,-862000000.0
Reconciled Depreciation,3747000000.0,2911000000.0,2322000000.0,2154000000.0
Reconciled Cost Of Revenue,60609000000.0,40217000000.0,24906000000.0,20509000000.0
EBITDA,17657000000.0,9625000000.0,4224000000.0,2174000000.0
EBIT,13910000000.0,6714000000.0,1902000000.0,20000000.0
Net Interest Income,106000000.0,-315000000.0,-718000000.0,-641000000.0
Interest Expense,191000000.0,371000000.0,748000000.0,685000000.0
Interest Income,297000000.0,56000000.0,30000000.0,44000000.0
Normalized Income,12744920000.0,5494970000.0,690000000.0,-753230000.0
Net Income From Continuing And Discontinued Operation,12583000000.0,5519000000.0,690000000.0,-862000000.0
Total Expenses,67630000000.0,47327000000.0,29542000000.0,24498000000.0
Total Operating Income As Reported,13656000000.0,-6523000000.0,1994000000.0,-69000000.0
Diluted Average Shares,3475000000.0,3387000000.0,3249000000.0,2661000000.0
Basic Average Shares,3130000000.0,2958000000.0,2799000000.0,2661000000.0
Diluted EPS,3.62,1.633333,0.213333,-0.326667
Basic EPS,4.02,1.866667,0.246667,-0.326667
Diluted NI Availto Com Stockholders,12584000000.0,5519000000.0,690000000.0,-862000000.0
Average Dilution Earnings,1000000.0,NaN,NaN,NaN
Net Income Common Stockholders,12583000000.0,5519000000.0,690000000.0,-862000000.0
Net Income,12583000000.0,5519000000.0,690000000.0,-862000000.0
Minority Interests,-4000000.0,-125000000.0,-172000000.0,-87000000.0
Net Income Including Noncontrolling Interests,12587000000.0,5644000000.0,862000000.0,-775000000.0
Net Income Continuous Operations,12587000000.0,5644000000.0,862000000.0,-775000000.0
Tax Provision,1132000000.0,699000000.0,292000000.0,110000000.0
Pretax Income,13719000000.0,6343000000.0,1154000000.0,-665000000.0
Other Income Expense,-219000000.0,162000000.0,-122000000.0,-104000000.0
Other Non Operating Income Expenses,-43000000.0,135000000.0,-122000000.0,45000000.0
Special Income Charges,-176000000.0,27000000.0,0.0,-149000000.0
Restructuring And Mergern Acquisition,176000000.0,-27000000.0,0.0,149000000.0
Net Non Operating Interest Income Expense,106000000.0,-315000000.0,-718000000.0,-641000000.0
Interest Expense Non Operating,191000000.0,371000000.0,748000000.0,685000000.0
Interest Income Non Operating,297000000.0,56000000.0,30000000.0,44000000.0
Operating Income,13832000000.0,6496000000.0,1994000000.0,80000000.0
Operating Expense,7021000000.0,7110000000.0,4636000000.0,3989000000.0
Research And Development,3075000000.0,2593000000.0,1491000000.0,1343000000.0
Selling General And Administration,3946000000.0,4517000000.0,3145000000.0,2646000000.0
Gross Profit,20853000000.0,13606000000.0,6630000000.0,4069000000.0
Cost Of Revenue,60609000000.0,40217000000.0,24906000000.0,20509000000.0
Total Revenue,81462000000.0,53823000000.0,31536000000.0,24578000000.0
Operating Revenue,81462000000.0,53823000000.0,31536000000.0,24578000000.0

In [15]:
tsla_bs_annual

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Ordinary Shares Number,3164000000.0,3099000000.0,2880000000.0,2715931290.0
Share Issued,3164000000.0,3099000000.0,2880000000.0,2715931290.0
Net Debt,NaN,NaN,NaN,7151000000.0
Total Debt,3099000000.0,6834000000.0,11739000000.0,13419000000.0
Tangible Book Value,44111000000.0,28472000000.0,21705000000.0,6081000000.0
...,...,...,...,...
Receivables,2952000000.0,1913000000.0,1886000000.0,1324000000.0
Accounts Receivable,2952000000.0,1913000000.0,1886000000.0,1324000000.0
Cash Cash Equivalents And Short Term Investments,22185000000.0,17707000000.0,19384000000.0,6268000000.0
Other Short Term Investments,5932000000.0,131000000.0,NaN,NaN
Cash And Cash Equivalents,22185000000.0,17576000000.0,19384000000.0,6268000000.0

In [16]:
tsla_cf_annual

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Free Cash Flow,7552000000.0,3483000000.0,2701000000.0,968000000.0
Repayment Of Debt,-3866000000.0,-14615000000.0,-12201000000.0,-389000000.0
Issuance Of Debt,0.0,8883000000.0,9713000000.0,10669000000.0
Issuance Of Capital Stock,0.0,0.0,12269000000.0,848000000.0
Capital Expenditure,-7172000000.0,-8014000000.0,-3242000000.0,-1437000000.0
Interest Paid Supplemental Data,152000000.0,266000000.0,444000000.0,455000000.0
Income Tax Paid Supplemental Data,1203000000.0,561000000.0,115000000.0,54000000.0
End Cash Position,16924000000.0,18144000000.0,19901000000.0,6783000000.0
Beginning Cash Position,18144000000.0,19901000000.0,6783000000.0,4277000000.0
Effect Of Exchange Rate Changes,-444000000.0,-183000000.0,334000000.0,8000000.0
Changes In Cash,-776000000.0,-1574000000.0,12784000000.0,2498000000.0
Financing Cash Flow,-3527000000.0,-5203000000.0,9973000000.0,1529000000.0
Cash Flow From Continuing Financing Activities,-3527000000.0,-5203000000.0,9973000000.0,1529000000.0
Net Other Financing Charges,-202000000.0,-178000000.0,-225000000.0,222000000.0
Proceeds From Stock Option Exercised,541000000.0,707000000.0,417000000.0,437000000.0
Net Common Stock Issuance,0.0,0.0,12269000000.0,848000000.0
Common Stock Issuance,0.0,0.0,12269000000.0,848000000.0
Net Issuance Payments Of Debt,-3866000000.0,-5732000000.0,-2488000000.0,459000000.0
Net Long Term Debt Issuance,-3866000000.0,-5732000000.0,-2488000000.0,459000000.0
Long Term Debt Payments,-3866000000.0,-14615000000.0,-12201000000.0,-389000000.0
Long Term Debt Issuance,0.0,8883000000.0,9713000000.0,10669000000.0
Investing Cash Flow,-11973000000.0,-7868000000.0,-3132000000.0,-1436000000.0
Cash Flow From Continuing Investing Activities,-11973000000.0,-7868000000.0,-3132000000.0,-1436000000.0
Net Other Investing Changes,76000000.0,6000000.0,123000000.0,46000000.0
Net Investment Purchase And Sale,-5813000000.0,-132000000.0,NaN,NaN
Sale Of Investment,22000000.0,NaN,NaN,NaN
Purchase Of Investment,-5835000000.0,-132000000.0,NaN,NaN
Net Business Purchase And Sale,0.0,0.0,-13000000.0,-45000000.0
Sale Of Business,0.0,NaN,NaN,NaN
Purchase Of Business,0.0,0.0,-13000000.0,-45000000.0
Net Intangibles Purchase And Sale,927000000.0,-1228000000.0,-10000000.0,-5000000.0
Sale Of Intangibles,936000000.0,272000000.0,NaN,NaN
Purchase Of Intangibles,-9000000.0,-1500000000.0,-10000000.0,-5000000.0
Net PPE Purchase And Sale,-7163000000.0,-6514000000.0,-3232000000.0,-105000000.0
Purchase Of PPE,-7163000000.0,-6514000000.0,-3232000000.0,-105000000.0
Capital Expenditure Reported,NaN,NaN,NaN,-1327000000.0
Operating Cash Flow,14724000000.0,11497000000.0,5943000000.0,2405000000.0
Cash Flow From Continuing Operating Activities,14724000000.0,11497000000.0,5943000000.0,2405000000.0
Change In Working Capital,-3908000000.0,518000000.0,184000000.0,-349000000.0
Change In Other Working Capital,1286000000.0,979000000.0,328000000.0,743000000.0
Change In Other Current Liabilities,1904000000.0,476000000.0,495000000.0,-41000000.0
Change In Other Current Assets,-4121000000.0,-3405000000.0,-1416000000.0,-649000000.0
Change In Payables And Accrued Expense,6029000000.0,4578000000.0,2102000000.0,682000000.0
Change In Prepaid Assets,-1417000000.0,-271000000.0,-251000000.0,-288000000.0
Change In Inventory,-6465000000.0,-1709000000.0,-422000000.0,-429000000.0
Change In Receivables,-1124000000.0,-130000000.0,-652000000.0,-367000000.0
Changes In Account Receivables,-1124000000.0,-130000000.0,-652000000.0,-367000000.0
Other Non Cash Items,340000000.0,245000000.0,408000000.0,477000000.0
Stock Based Compensation,1560000000.0,2121000000.0,1734000000.0,898000000.0
Asset Impairment Charge,177000000.0,140000000.0,202000000.0,193000000.0
Depreciation Amortization Depletion,3747000000.0,2911000000.0,2322000000.0,2154000000.0
Depreciation And Amortization,3747000000.0,2911000000.0,2322000000.0,2154000000.0
Depreciation,3747000000.0,2911000000.0,NaN,NaN
Operating Gains Losses,221000000.0,-82000000.0,231000000.0,98000000.0
Net Foreign Currency Exchange Gain Loss,81000000.0,-55000000.0,114000000.0,-48000000.0
Gain Loss On Sale Of PPE,140000000.0,-27000000.0,117000000.0,146000000.0
Net Income From Continuing Operations,12587000000.0,5644000000.0,862000000.0,-775000000.0

In [17]:
# show holders - Major Holders, Institutional Holders, Mutual Fund Holders
tsla.major_holders

        0                                      1
0  13.04%        % of Shares Held by All Insider
1  44.21%       % of Shares Held by Institutions
2  50.84%        % of Float Held by Institutions
3    3506  Number of Institutions Holding Shares

In [18]:
tsla.institutional_holders

,Holder,Shares,Date Reported,% Out,Value
0,Vanguard Group Inc,222486933,2023-06-29,0.0701,59246047289
1,Blackrock Inc.,185889398,2023-06-29,0.0586,49500489381
2,State Street Corporation,104115390,2023-06-29,0.0328,27724888092
3,"Geode Capital Management, LLC",51656526,2023-06-29,0.0163,13755616749
4,Capital World Investors,42272512,2023-06-29,0.0133,11256747581
5,"FMR, LLC",28771552,2023-06-29,0.0091,7661576827
6,Norges Bank Investment Management,28085245,2022-12-30,0.0088,7478820131
7,Price (T.Rowe) Associates Inc,27984161,2023-06-29,0.0088,7451902471
8,Morgan Stanley,27983350,2023-06-29,0.0088,7451686510
9,JP Morgan Chase & Company,26739940,2023-06-29,0.0084,7120578851

In [19]:
tsla.mutualfund_holders

,Holder,Shares,Date Reported,% Out,Value
0,Vanguard Total Stock Market Index Fund,84022098,2023-06-29,0.0265,22374245194
1,Vanguard 500 Index Fund,64144346,2023-06-29,0.0202,17080998444
2,Fidelity 500 Index Fund,30095622,2023-05-30,0.0095,8014163439
3,SPDR S&P 500 ETF Trust,29683481,2023-08-30,0.0094,7904414409
4,"Invesco ETF Tr-Invesco QQQ Tr, Series 1 ETF",25046231,2023-08-30,0.0079,6669561067
5,iShares Core S&P 500 ETF,25198117,2023-08-30,0.0079,6710006791
6,Growth Fund Of America Inc,23446964,2023-06-29,0.0074,6243692243
7,Vanguard Growth Index Fund,22921725,2023-06-29,0.0072,6103826346
8,Vanguard Institutional Index Fund-Institutiona...,18390595,2023-06-29,0.0058,4897231699
9,Select Sector SPDR Fund-Consumer Discretionary,12989732,2023-08-30,0.0041,3459035845

In [20]:
# Show future and historic earnings dates, 
tsla.get_earnings_dates(limit=20)

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2024-07-17 06:00:00-04:00           NaN           NaN          NaN
2024-04-17 06:00:00-04:00           NaN           NaN          NaN
2024-01-23 16:00:00-05:00           NaN           NaN          NaN
2024-01-23 05:00:00-05:00           NaN           NaN          NaN
2023-10-18 17:00:00-04:00          0.74           NaN          NaN
2023-10-18 16:00:00-04:00          0.74           NaN          NaN
2023-07-19 12:00:00-04:00          0.82          0.91       0.1063
2023-04-19 12:00:00-04:00          0.85          0.85      -0.0004
2023-01-25 11:00:00-05:00          1.13          1.19       0.0555
2022-10-19 12:00:00-04:00          0.99          1.05       0.0570
2022-07-20 12:00:00-04:00          0.60          0.76       0.2511
2022-04-20 12:00:00-04:00          0.75          1.07       0.4256
2022-01-26 11:00:00-05:00          0.79          0.85       0.0715
2021-10-20 12:00:00-04:00          0.53          0.62       0.1668
2021-07-26 12:00:00-04:00          0.33          0.48       0.4770
2021-04-26 12:00:00-04:00          0.26          0.31       0.1777
2021-01-27 11:00:00-05:00          0.34          0.27      -0.2252
2020-10-21 12:00:00-04:00          0.19          0.25       0.3072
2020-07-22 12:00:00-04:00         -0.01          0.15      12.8347
2020-04-29 12:00:00-04:00         -0.02          0.08       4.5681

In [21]:
# show options expirations
tsla.options

('2023-10-13',
 '2023-10-20',
 '2023-10-27',
 '2023-11-03',
 '2023-11-10',
 '2023-11-17',
 '2023-11-24',
 '2023-12-15',
 '2024-01-19',
 '2024-02-16',
 '2024-03-15',
 '2024-04-19',
 '2024-05-17',
 '2024-06-21',
 '2024-09-20',
 '2025-01-17',
 '2025-06-20',
 '2025-09-19',
 '2025-12-19',
 '2026-01-16')

In [22]:
# show news
tsla.news

[{'uuid': '1e8dfc51-408a-33e2-98cc-796e83a5e9ac',
  'title': 'Tesla rejects union claims, reports of health and safety issues at German plant',
  'publisher': 'Reuters',
  'link': 'https://finance.yahoo.com/news/tesla-rejects-union-claims-reports-161903981.html',
  'providerPublishTime': 1696954743,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/MGIMBqw.Grbye8KSQiurJg--~B/aD01MzQ7dz04MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/reuters-finance.com/28860dde6f1fd303693a3e988b68949f',
     'width': 800,
     'height': 534,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/SD.aaIteEZrOXOzE7PbGNA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/reuters-finance.com/28860dde6f1fd303693a3e988b68949f',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['TSLA']},
 {'uuid': '93d40fff-f95b-3fe7-b238-03f049ef4acb',
  'title': 'Tesla Stock Flashes Buy Signal Even As Wall Street Tempers View With Q3 Earnings Due Next Week',
  'publisher': "Investor's Business Daily",
  'link': 'https://finance.yahoo.com/m/93d40fff-f95b-3fe7-b238-03f049ef4acb/tesla-stock-flashes-buy.html',
  'providerPublishTime': 1696953269,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/3nRm9DQCMm3sPr2Y954gYQ--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/1cd136b0155094cbff6ef7e10ec01076',
     'width': 1000,
     'height': 563,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/edfbotpZRbxkReP8Wq2DOQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/1cd136b0155094cbff6ef7e10ec01076',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['TSLA']},
 {'uuid': '0e42513e-6a19-338a-95fd-a6d26d333f30',
  'title': 'Top automaker may be about to unveil the ultimate Tesla killer',
  'publisher': 'TheStreet.com',
  'link': 'https://finance.yahoo.com/m/0e42513e-6a19-338a-95fd-a6d26d333f30/top-automaker-may-be-about-to.html',
  'providerPublishTime': 1696952940,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/RmqDg7ptTw8.yGa6V4PtJQ--~B/aD00NDgwO3c9NjcyMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/thestreet.com/5364976ed0fc69b44d794a42c8b28e89',
     'width': 6720,
     'height': 4480,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/SaIVrH5MrwtFCuiMviuBbw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/thestreet.com/5364976ed0fc69b44d794a42c8b28e89',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['TSLA']},
 {'uuid': 'aefcee51-758a-3023-8c3a-f53c0e93c94e',
  'title': "Elon Musk makes a big move to compete with Jeff Bezos' Amazon",
  'publisher': 'TheStreet.com',
  'link': 'https://finance.yahoo.com/m/aefcee51-758a-3023-8c3a-f53c0e93c94e/elon-musk-makes-a-big-move-to.html',
  'providerPublishTime': 1696952640,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/HizSFBy3AAOATAt9dF8mgA--~B/aD0xMDgwO3c9MTkyMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/thestreet.com/8d3cc450c3b69894bf0e915bcc7ee387',
     'width': 1920,
     'height': 1080,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/bKM.6RGhBsw.GshPd6wjGg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/thestreet.com/8d3cc450c3b69894bf0e915bcc7ee387',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['TSLA', 'AMZN']},
 {'uuid': '3020e7c4-670a-3513-94d9-6a64736dbb15',
  'title': 'Tesla rival Lucid delivers an exciting surprise to customers',
  'publisher': 'TheStreet.com',
  'link': 'https://finance.yahoo.com/m/3020e7c4-670a-3513-94d9-6a64736dbb15/tesla-rival-lucid-delivers-an.html',
  'providerPublishTime': 1696952400,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/g6Crs_TbrSQlyyeNy83UBQ--~B/aD0xMDgwO3c9MTkyMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/thestreet.com/d94f3a7efaa20ef6300985a4bdc83a67',
     'width': 1920,
     'height': 1080,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/6pmvBYya9A9bV635qzdR0w--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/thestreet.com/d94f3a7efaa20ef6300985a4bdc83a67',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['TSLA']},
 {'uuid': 'cc69a47f-1b6a-39bf-80e1-1895a2a803e7',
  'title': 'Magnificent Seven May Be Gearing Up For Fantastic Finish To 2023',
  'publisher': "Investor's Business Daily",
  'link': 'https://finance.yahoo.com/m/cc69a47f-1b6a-39bf-80e1-1895a2a803e7/magnificent-seven-may-be.html',
  'providerPublishTime': 1696950682,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/GxVJSCi7Sm3J.qWcporUkQ--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/77f73ad383824602ae6fb9b455cc5a85',
     'width': 1000,
     'height': 563,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/aGm46_ix3E.b72hIe7Aofg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/77f73ad383824602ae6fb9b455cc5a85',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT', 'NVDA', 'META', 'TSLA', 'GOOGL', 'AAPL', 'AMZN']},
 {'uuid': 'b0034d19-3fa5-314e-9498-c59352fd5091',
  'title': 'Dow Jones Rallies As Treasury Yields Slide; 6 Best Stocks To Buy And Watch',
  'publisher': "Investor's Business Daily",
  'link': 'https://finance.yahoo.com/m/b0034d19-3fa5-314e-9498-c59352fd5091/dow-jones-rallies-as-treasury.html',
  'providerPublishTime': 1696948680,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/DIEhIoFnsXUM5iPvkou0LQ--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/b93082b62d669a716dcee1724ff49dd4',
     'width': 1000,
     'height': 563,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/6B00yQ3tJw8OlbCKfMOrhA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/b93082b62d669a716dcee1724ff49dd4',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['^DJI',
   'TSLA',
   'DKNG',
   'AAPL',
   'COMP',
   'DUOL',
   '^GSPC',
   'ANET',
   'CVX']},
 {'uuid': '05dba138-ecd4-3c50-a7c1-50d94455dc52',
  'title': 'Tesla higher even as 2 more Wall Street analysts cut targets ahead of Q3 earnings',
  'publisher': 'TheStreet.com',
  'link': 'https://finance.yahoo.com/m/05dba138-ecd4-3c50-a7c1-50d94455dc52/tesla-higher-even-as-2-more.html',
  'providerPublishTime': 1696947480,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/hGnm1pbrUMBJE8wRfaHtiw--~B/aD0xMDgwO3c9MTkyMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/thestreet.com/984dc45f29a058d7052d2fa4d44cc0b2',
     'width': 1920,
     'height': 1080,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/wLbRmKz.I2hgXuSpkuTDGg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/thestreet.com/984dc45f29a058d7052d2fa4d44cc0b2',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['TSLA']}]